from flask import Flask, jsonify, request, render_template, send_from_directory
from datetime import datetime
from dotenv import load_dotenv
from werkzeug.utils import secure_filename
from psycopg.rows import dict_row
from vercel.blob import AsyncBlobClient

import asyncio
import os
import sqlite3


load_dotenv()

app = Flask(__name__)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE_DIR, "songs.db")
UPLOAD_DIR = os.path.join(BASE_DIR, "uploads")
os.makedirs(UPLOAD_DIR, exist_ok=True)

SHEET_EXTS = {"pdf", "png", "jpg", "jpeg"}
AUDIO_EXTS = {"mp3", "wav", "m4a", "ogg", "aac", "flac"}
FILE_FIELDS = ["chord_sheet", "lead_sheet", "jianpu", "audio"]
PATH_FIELDS = {field: f"{field}_path" for field in FILE_FIELDS}


def database_url():
    return os.environ.get("POSTGRES_URL") or os.environ.get("DATABASE_URL") or ""


def has_remote_storage():
    return bool(database_url()) and bool(os.environ.get("BLOB_READ_WRITE_TOKEN"))


def use_postgres():
    return bool(database_url())


app.config["MAX_CONTENT_LENGTH"] = int((4.5 if has_remote_storage() else 50) * 1024 * 1024)


def get_db():
    if use_postgres():
        import psycopg

        conn = psycopg.connect(database_url(), row_factory=dict_row)
        return conn

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def song_table_sql():
    if use_postgres():
        return """
            CREATE TABLE IF NOT EXISTS songs (
                id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title           TEXT NOT NULL,
                title_zh        TEXT,
                key             TEXT,
                beats           TEXT,
                chord_sheet     TEXT,
                chord_sheet_path TEXT,
                lead_sheet      TEXT,
                lead_sheet_path TEXT,
                jianpu          TEXT,
                jianpu_path     TEXT,
                audio           TEXT,
                audio_path      TEXT,
                youtube_url     TEXT,
                remark          TEXT,
                created_at      TEXT
            )
        """

    return """
        CREATE TABLE IF NOT EXISTS songs (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            title           TEXT NOT NULL,
            title_zh        TEXT,
            key             TEXT,
            beats           TEXT,
            chord_sheet     TEXT,
            chord_sheet_path TEXT,
            lead_sheet      TEXT,
            lead_sheet_path TEXT,
            jianpu          TEXT,
            jianpu_path     TEXT,
            audio           TEXT,
            audio_path      TEXT,
            youtube_url     TEXT,
            remark          TEXT,
            created_at      TEXT
        )
    """


def init_db():
    with get_db() as conn:
        conn.execute(song_table_sql())

    if not use_postgres():
        ensure_sqlite_columns()


def ensure_sqlite_columns():
    with get_db() as conn:
        existing = {
            row["name"] if isinstance(row, sqlite3.Row) else row[1]
            for row in conn.execute("PRAGMA table_info(songs)").fetchall()
        }
        required = {
            "chord_sheet_path",
            "lead_sheet_path",
            "jianpu_path",
            "audio_path",
        }
        for col in sorted(required - existing):
            conn.execute(f"ALTER TABLE songs ADD COLUMN {col} TEXT")


init_db()


def ext_of(filename):
    return filename.rsplit(".", 1)[-1].lower() if "." in filename else ""


def allowed(filename, field):
    e = ext_of(filename)
    return e in (AUDIO_EXTS if field == "audio" else SHEET_EXTS)


def blob_path(song_id, field, filename):
    safe_name = secure_filename(filename) or f"{field}.{ext_of(filename) or 'bin'}"
    stamp = datetime.now().strftime("%Y%m%d%H%M%S")
    return f"songs/{song_id}/{field}/{stamp}_{safe_name}"


async def upload_blob(pathname, data):
    client = AsyncBlobClient()
    blob = await client.put(pathname, data, access="public", add_random_suffix=True)
    return {"url": blob.url, "pathname": blob.pathname}


async def delete_blob(pathname):
    if not pathname:
        return
    client = AsyncBlobClient()
    for method_name in ("delete", "del", "remove"):
        method = getattr(client, method_name, None)
        if not method:
            continue
        result = method(pathname)
        if asyncio.iscoroutine(result):
            await result
        return
    raise RuntimeError("Blob delete method not available")


def run_async(coro):
    return asyncio.run(coro)


def save_upload(file, field, song_id):
    if not file or not file.filename:
        return None
    if not allowed(file.filename, field):
        return None

    if has_remote_storage():
        pathname = blob_path(song_id, field, file.filename)
        payload = file.read()
        return run_async(upload_blob(pathname, payload))

    filename = secure_filename(f"{song_id}_{field}.{ext_of(file.filename)}")
    file.save(os.path.join(UPLOAD_DIR, filename))
    return {"url": filename, "pathname": filename}


def remove_upload(value, pathname):
    if has_remote_storage():
        if pathname:
            run_async(delete_blob(pathname))
        return

    target = pathname or value
    if target:
        path = os.path.join(UPLOAD_DIR, target)
        if os.path.exists(path):
            os.remove(path)


def row_to_dict(row):
    return dict(row) if row else None


def song_order_clause():
    return "ORDER BY LOWER(title)"


def fetch_songs():
    with get_db() as conn:
        rows = conn.execute(f"SELECT * FROM songs {song_order_clause()}").fetchall()
    return [row_to_dict(r) for r in rows]


def fetch_song(song_id):
    with get_db() as conn:
        row = conn.execute("SELECT * FROM songs WHERE id=?", (song_id,)).fetchone() if not use_postgres() else conn.execute("SELECT * FROM songs WHERE id=%s", (song_id,)).fetchone()
    return row_to_dict(row)


def fetch_song_by_id_for_update(conn, song_id):
    if use_postgres():
        row = conn.execute("SELECT * FROM songs WHERE id=%s", (song_id,)).fetchone()
    else:
        row = conn.execute("SELECT * FROM songs WHERE id=?", (song_id,)).fetchone()
    return row_to_dict(row)


def insert_song(row):
    if use_postgres():
        sql = """
            INSERT INTO songs (
                title,title_zh,key,beats,
                chord_sheet,chord_sheet_path,
                lead_sheet,lead_sheet_path,
                jianpu,jianpu_path,
                audio,audio_path,
                youtube_url,remark,created_at
            )
            VALUES (
                %(title)s,%(title_zh)s,%(key)s,%(beats)s,
                %(chord_sheet)s,%(chord_sheet_path)s,
                %(lead_sheet)s,%(lead_sheet_path)s,
                %(jianpu)s,%(jianpu_path)s,
                %(audio)s,%(audio_path)s,
                %(youtube_url)s,%(remark)s,%(created_at)s
            )
            RETURNING *
        """
        with get_db() as conn:
            r = conn.execute(sql, row).fetchone()
        return row_to_dict(r)

    with get_db() as conn:
        cur = conn.execute(
            """
            INSERT INTO songs (
                title,title_zh,key,beats,
                chord_sheet,chord_sheet_path,
                lead_sheet,lead_sheet_path,
                jianpu,jianpu_path,
                audio,audio_path,
                youtube_url,remark,created_at
            )
            VALUES (
                :title,:title_zh,:key,:beats,
                :chord_sheet,:chord_sheet_path,
                :lead_sheet,:lead_sheet_path,
                :jianpu,:jianpu_path,
                :audio,:audio_path,
                :youtube_url,:remark,:created_at
            )
            """,
            row,
        )
        song_id = cur.lastrowid
        r = conn.execute("SELECT * FROM songs WHERE id=?", (song_id,)).fetchone()
    return row_to_dict(r)


def update_song_row(song_id, row):
    row["id"] = song_id
    if use_postgres():
        with get_db() as conn:
            conn.execute(
                """
                UPDATE songs SET
                    title=%(title)s,
                    title_zh=%(title_zh)s,
                    key=%(key)s,
                    beats=%(beats)s,
                    chord_sheet=%(chord_sheet)s,
                    chord_sheet_path=%(chord_sheet_path)s,
                    lead_sheet=%(lead_sheet)s,
                    lead_sheet_path=%(lead_sheet_path)s,
                    jianpu=%(jianpu)s,
                    jianpu_path=%(jianpu_path)s,
                    audio=%(audio)s,
                    audio_path=%(audio_path)s,
                    youtube_url=%(youtube_url)s,
                    remark=%(remark)s
                WHERE id=%(id)s
                """,
                row,
            )
            r = conn.execute("SELECT * FROM songs WHERE id=%s", (song_id,)).fetchone()
        return row_to_dict(r)

    with get_db() as conn:
        conn.execute(
            """
            UPDATE songs SET
                title=:title,
                title_zh=:title_zh,
                key=:key,
                beats=:beats,
                chord_sheet=:chord_sheet,
                chord_sheet_path=:chord_sheet_path,
                lead_sheet=:lead_sheet,
                lead_sheet_path=:lead_sheet_path,
                jianpu=:jianpu,
                jianpu_path=:jianpu_path,
                audio=:audio,
                audio_path=:audio_path,
                youtube_url=:youtube_url,
                remark=:remark
            WHERE id=:id
            """,
            row,
        )
        r = conn.execute("SELECT * FROM songs WHERE id=?", (song_id,)).fetchone()
    return row_to_dict(r)


def delete_song_row(song_id):
    with get_db() as conn:
        if use_postgres():
            conn.execute("DELETE FROM songs WHERE id=%s", (song_id,))
        else:
            conn.execute("DELETE FROM songs WHERE id=?", (song_id,))


def song_exists(song_id):
    return fetch_song(song_id)


@app.route("/")
def index():
    return render_template("songs.html")


@app.route("/songs", methods=["GET"])
def get_songs():
    return jsonify(fetch_songs())


@app.route("/songs", methods=["POST"])
def add_song():
    title = (request.form.get("title") or "").strip()
    if not title:
        return jsonify({"error": "Title is required"}), 400

    row = {
        "title": title,
        "title_zh": (request.form.get("title_zh") or "").strip(),
        "key": (request.form.get("key") or "").strip(),
        "beats": (request.form.get("beats") or "").strip(),
        "chord_sheet": None,
        "chord_sheet_path": None,
        "lead_sheet": None,
        "lead_sheet_path": None,
        "jianpu": None,
        "jianpu_path": None,
        "audio": None,
        "audio_path": None,
        "youtube_url": (request.form.get("youtube_url") or "").strip(),
        "remark": (request.form.get("remark") or "").strip(),
        "created_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
    }

    created = insert_song(row)
    song_id = created["id"]

    updates = {}
    for field in FILE_FIELDS:
        uploaded = save_upload(request.files.get(field), field, song_id)
        if uploaded:
            updates[field] = uploaded["url"]
            updates[PATH_FIELDS[field]] = uploaded["pathname"]

    if updates:
        created.update(updates)
        created = update_song_row(song_id, created)

    return jsonify(created), 201


@app.route("/songs/<int:song_id>", methods=["PUT"])
def update_song(song_id):
    existing = song_exists(song_id)
    if not existing:
        return jsonify({"error": "Song not found"}), 404

    title = (request.form.get("title") or "").strip()
    if not title:
        return jsonify({"error": "Title is required"}), 400

    row = {
        "title": title,
        "title_zh": (request.form.get("title_zh") or "").strip(),
        "key": (request.form.get("key") or "").strip(),
        "beats": (request.form.get("beats") or "").strip(),
        "youtube_url": (request.form.get("youtube_url") or "").strip(),
        "remark": (request.form.get("remark") or "").strip(),
        "chord_sheet": existing.get("chord_sheet"),
        "chord_sheet_path": existing.get("chord_sheet_path"),
        "lead_sheet": existing.get("lead_sheet"),
        "lead_sheet_path": existing.get("lead_sheet_path"),
        "jianpu": existing.get("jianpu"),
        "jianpu_path": existing.get("jianpu_path"),
        "audio": existing.get("audio"),
        "audio_path": existing.get("audio_path"),
    }

    for field in FILE_FIELDS:
        path_field = PATH_FIELDS[field]
        new_file = request.files.get(field)
        if new_file and new_file.filename:
            remove_upload(existing.get(field), existing.get(path_field))
            uploaded = save_upload(new_file, field, song_id)
            row[field] = uploaded["url"] if uploaded else None
            row[path_field] = uploaded["pathname"] if uploaded else None
        elif request.form.get(f"clear_{field}") == "1":
            remove_upload(existing.get(field), existing.get(path_field))
            row[field] = None
            row[path_field] = None

    updated = update_song_row(song_id, row)
    return jsonify(updated)


@app.route("/songs/<int:song_id>", methods=["DELETE"])
def delete_song(song_id):
    existing = song_exists(song_id)
    if not existing:
        return jsonify({"error": "Song not found"}), 404

    for field in FILE_FIELDS:
        remove_upload(existing.get(field), existing.get(PATH_FIELDS[field]))

    delete_song_row(song_id)
    return jsonify({"deleted": song_id})


@app.route("/uploads/<path:filename>")
def serve_upload(filename):
    return send_from_directory(UPLOAD_DIR, filename)


if __name__ == "__main__":
    app.run(debug=True, port=5001)
